version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3050:80

  client:
    container_name: client
    build: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000

  api:
    container_name: api
    build: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mongo
    ports:
      - 4000:4000
    environment:
      - MONGO_URL=mongodb://api:docker1234@mongo:27017/?authMechanism=DEFAULT
      - JWT_SECRET=test

  mongo:
    container_name: mongo_DB
    image: mongo
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
